name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_merge_dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Dependabot PR
        if: github.actor == 'dependabot[bot]'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
